brailleweb/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/', include('webapp.urls')),
    path('', views.index)
]

webapp/urls.py
from . import views
from django.urls import include, path

app_name = 'webapp'
urlpatterns = [
    path('uploadfile/', views.upload_file_form, name='upload_file_form'),
    path('uploadtext/', views.text_form, name='text_form'),
    path('downloadfile/', views.download_file, name='download_file'),
    path('showtext/', views.get_text, name='show_text'),
    path('texts/', views.text_list, name='text_list'),
]

webapp/models.py
from django.conf import settings
from django.db import models
from django.core.files.storage import FileSystemStorage

# Create your models here.

sendfile_storage = FileSystemStorage(location=settings.SENDFILE_ROOT)


def default_upload_path(instance, filename):
    return 'public/{0}/'.format(filename)

class UploadFile(models.Model):
    file = models.FileField(("Upload File"), upload_to=default_upload_path)
    active = models.BooleanField(default=True)
    
    def save(self, *args, **kwargs):
        # Override file if existing
        if self.pk is not None and self.file is not None:
            self.file.delete()
            self.delete()
        super(UploadFile, self).save(*args, **kwargs)

class Text(models.Model):
    content = models.TextField()
    active = models.BooleanField(default=True)

webapp/forms.py
from django import forms
from .models import UploadFile, Text


class UploadFileForm(forms.ModelForm):
    
    class Meta:
        model = UploadFile
        exclude = ['active']

class DefaultForm(forms.ModelForm):
    
    class Meta:
        model = Text
        exclude = ['active']

webapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import UploadFileForm, DefaultForm
from .models import UploadFile, Text
from django.shortcuts import get_object_or_404
import os
from django.core.files import File
from django.contrib import messages

def index(request):
    return render(request, 'webapp/base.html')
# Create your views here.
def upload_file_form(request):
    if request.method == "POST":
        success = False
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                success = True
            except Exception as e:
                success = False
                print(e)
        if not success:
            messages.error(request, "Failed to save!")
        else:
            messages.success(request, "Entry saved!")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = UploadFileForm()
    return render(
        request,
        'webapp/upload_file_form.html',
        {'form': form}
    )

def text_form(request):
    if request.method == "POST":
        success = False
        form = DefaultForm(request.POST)
        if form.is_valid():
            try:
                obj = form.save()
                myFile = None
                with open(str(obj.pk)+'.txt', 'w') as f:
                    myFile = File(f)
                    myFile.write(str(obj.content))
                f = open(str(obj.pk)+'.txt', 'r')
                myFile = File(f)
                upload_file = UploadFile(file=myFile, active=True)
                upload_file.save()
                myFile.close()
                f.close()
                print(upload_file.file.name)
                success = True
            except Exception as e:
                success = False
                print(e)
        if not success:
            messages.error(request, "Failed to save!")
        else:
            messages.success(request, "Entry saved!")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = DefaultForm()
    return render(
        request,
        'webapp/text_form.html',
        {'form': form}
    )

from django.http import Http404

def download_file(request):
    try:
        obj = UploadFile.objects.filter(active=True)[0]
    except:
        raise Http404('Nao tem download')
    file_path = obj.file.path

    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type='application/force-download')
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            obj.active = False
            obj.save()
            return response
    else:
        obj.active = False
        obj.save()
        raise Http404(str(file_path)+ ' nao encontrado')

def get_text(request):
    obj = get_object_or_404(Text, active=True)
    obj.active = False
    obj.save()
    return HttpResponse(obj.content)

def text_list(request):
    objs = Text.objects.filter(active=True)
    
    return render(request, 'webapp/text_list.html', {'objs': objs})

templates/webapp/base.html
{% extends 'adminlte/base.html' %}
{% load bootstrap3 %}
{% load adminlte_helpers %}
{% block title_outer %}
        <title>{% block title %}Impressora/Scanner Braille{% endblock %}</title>
{% endblock %}
{% block nav_sidebar %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

            {% block nav_links %}
                <li>
                    <a href="{% url 'webapp:upload_file_form' %}">
                        <i class="fa fa-upload"></i> <span>Enviar Arquivo</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'webapp:text_form' %}">
                        <i class="fa fa-file-text"></i> <span>Enviar Texto</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'webapp:text_list' %}">
                        <i class="fa fa-file-text"></i> <span>Lista de Textos</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'webapp:download_file' %}">
                        <i class="fa fa-download"></i> <span>Baixar Arquivo</span>
                    </a>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>
{% endblock %}

templates/webapp/text_form.html
{% extends 'webapp/base.html' %}
{% load bootstrap3 %}

{% block title %}Formulário de Texto{% endblock %}

{% block content %}
<div class="row">
    
  <div class="col-xs-12 col-md-7 left">
    <div class="box">
        <div class="box-header">
          <h3 class="box-title">Insira um texto</h3>
        </div>
        <!-- /.box-header -->
        <form action="{% url 'webapp:text_form' %}" role="form" method="POST" class="form">
          <div class="box-body">
              {% csrf_token %}
              {% bootstrap_form form %}
              {% buttons %}
                <a class="btn btn-default go_back" href="#" onclick="history.go(-1)">
                    <i class="fa fa-history"></i> Voltar
                </a>
                <button type="submit" class="btn btn-primary">
                  <i class="fa fa-save"></i> Salvar
                </button>
              {% endbuttons %}
          </div>
        </form>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
      <!-- /.box -->
  </div>
</div>
{% endblock %}

{% block extrajs %}
<!-- bootstrap datepicker -->
<!-- page script -->
<script>
  window.onresize = function(event) {
    var $iW = $(window).innerWidth();
    if ($iW < 976){
       $('.right').insertBefore('.left');
    }else{
       $('.right').insertAfter('.left');
    }
  }
</script>
{% endblock %}

templates/webapp/text_list.html
{% extends 'webapp/base.html' %}
{% load bootstrap3 %}

{% block title %}Lista de Textos{% endblock %}
{% block extrastyle %}
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-xs-12 col-md-7 left">
    <div class="box">
        <div class="box-header">
          <h3 class="box-title">Listagem de textos</h3>
        </div>
        
        {% for obj in objs %}
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{obj.id}}">
                Texto {{obj.id}}
            </button>
            
            <!-- Modal -->
            <div class="modal fade" id="{{obj.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Texto {{obj.id}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                    {{ obj.content }}
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
      <!-- /.box -->
  </div>
</div>
{% endblock %}

{% block extrajs %}
<!-- bootstrap datepicker -->
<!-- page script -->
<script>
  window.onresize = function(event) {
    var $iW = $(window).innerWidth();
    if ($iW < 976){
       $('.right').insertBefore('.left');
    }else{
       $('.right').insertAfter('.left');
    }
  }
</script>
{% endblock %}

templates/webapp/upload_file_form.html
{% extends 'webapp/base.html' %}
{% load bootstrap3 %}
{% block title %}
  Formulário Upload de Arquivo
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-xs-12 col-md-7 left">
    <div class="box">
        <div class="box-header">
          <h3 class="box-title">Formulário Upload de Arquivo</h3>
        </div>
        <!-- /.box-header -->
        <form action="{% url 'webapp:upload_file_form' %}" role="form" method="POST" class="form" enctype="multipart/form-data">
          <div class="box-body">
              {% csrf_token %}
              {% bootstrap_form form %}
              {% buttons %}
                <a class="btn btn-default go_back" href="#" onclick="history.go(-1)">
                    <i class="fa fa-history"></i> Voltar
                </a>
                <button type="submit" class="btn btn-primary">
                  <i class="fa fa-save"></i> Salvar
                </button>
              {% endbuttons %}
          </div>
        </form>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
      <!-- /.box -->
  </div>
</div>
{% endblock %}

{% block extrajs %}
<!-- bootstrap datepicker -->
<!-- page script -->
<script>
  window.onresize = function(event) {
    var $iW = $(window).innerWidth();
    if ($iW < 976){
       $('.right').insertBefore('.left');
    }else{
       $('.right').insertAfter('.left');
    }
  }
</script>
{% endblock %}